theme: the-plain

plugins:
  - jekyll-remote-theme
  
markdown: GFM
  
remote_theme: heiswayi/the-plain

# Site Info
title:              "Sarah {Aguasvivas Manzano}"
description:        "PhD Student"
author_name:        "Sarah Aguasvivas Manzano" # change this to your name
logo_url:           "img/picture_website2.png" # Get it from GitHub API: https://api.github.com/users/<username>
